stages:
  - install

install-requirements:
  stage: install
  tags:
    - your-runner-tag  # Replace with your GitLab runner tag
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
