stages:
  - test
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

test:
  stage: test
  image: python:3.10
  services:
    - postgres:14
  variables:
    POSTGRES_DB: tasks
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest tests/

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  script:
    - echo "Deploying $IMAGE_TAG"
    # You can integrate SSH or Helm commands here
