stages:
  - install

install-requirements:
  stage: install
  
  script:
    - cd task-tracker-api
    - rm -rf venv
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
